yajra/laravel-datatables-buttons

src/resources/assets/buttons.server-side.js

Hi, I added support for rendering 2 tables in a single page.
The idea was pretty simple. 
I had 2 tables in `/users`, `ActiveUsersDataTable` and `InactiveUsersDataTable`.
- I added and `id` field to use in html part of the datatable so that the ids won't conflict.
- I added `?tableId=TableID` to each request so that we can define which table we're querying with the ajax request to the backend.
- I edited the `server-side.buttons.js` to allow urls with a query parameter.

Fix ajax parameters when ? was used on based url.

---

src/Services/DataTable.php

Allow dataTable class modification via controller:
```php
public function index(ArticlesDataTable $dataTable)
{
return $dataTable->addScope(new OwnedScope))
->withHtml(function (Builder $builder) {
$builder->columns(['id']);
})
->render('articles::index');
}
```

Add html builder callback for code reusability.

---

src/Services/DataTable.php

Ex:
```php
public function index(ArticlesDataTable $dataTable)
{
return $dataTable->addScope(new OwnedScope))
->before(function (EloquentEngine $engine) {
$engine->editColumn('action', 'articles.datatables.action');
})
->withHtml(function (Builder $builder) {
$builder->removeColumn('articles.is_page', 'articles.hits');
})
->render('articles::index');
}
```

Do not require return from before callback closure.

---

src/Generators/DataTablesMakeCommand.php
src/Generators/stubs/datatables.stub
src/config/config.php

Hello,
i've added some options to the DataTable Generator :
- **model-namespace** : 
> allow to overwrite the namespace set in config 
>  implictly enable --model option
> usage : --model-namespace="Models\Client\"
- **columns** :
>  allow to set custom columns
> usage : --columns="id,label,url,address"
- **action** : 
> allow to choose the view to use for column action
> usage : --action="client.action"
i've also introduced a way to use a custom datatables.stub.
if something is wrong, tell me and i will correct it.
thanks

Adding model-namespace, columns and action options to Generator

---

src/Services/DataTable.php

This will allow to create custom button actions, or disable existing ones so they cannot be called by creating a custom request

Allow to add custom button actions (or disable already existing ones).

---

src/Generators/stubs/datatables.stub

Include `dom` for buttons by default.

Include builder parameters on stub to assist new users.

---

src/Services/DataTable.php

Hello, it seems dataTables method used in ajax method when fetching data is missing and results in a fatal error.

[2.0] Added missing dataTable method

---

src/Services/DataTable.php

Hello,
i'm adding dataTableVariable property to Services/DataTables.
The default value is dataTable like before, but can be overwritten by setting the dataTableVariable property in our custom dataTable class :
```
$dataTableVariable = 'MyDataTable';
```
Thanks.

Adding dataTableVariable property to Services/DataTables

---

src/resources/assets/buttons.server-side.js

Use `postCsv` as button. This button is recommended for IE browsers since IE has URL length limit.

Add export CSV with post as a method.

---

src/resources/assets/buttons.server-side.js

Use exportPostPdf as button. This button is recommended for IE browsers since IE has URL length limit.

Add export PDF with post as a method.

---

src/resources/assets/buttons.server-side.js

Use exportPostExcel as button. This button is recommended for IE browsers since IE has URL length limit.

Add export Excel with post as a method.

---

src/Generators/DataTablesMakeCommand.php
src/Generators/stubs/datatables.stub
src/Services/DataTable.php

- Suffixed `date('YmdHis')` instead of `time()`
- Use the original name passed to the make command
For example: `$ php artisan datatables:make AdminUserDataTable`
Old: `adminuserdatatable_1509263506`
New: `AdminUser_20171029075326`
Maybe more readable.

Change the default export filename

---

src/resources/assets/buttons.server-side.js

I figured it would make sense for the `reset` button to also reset column based searches. Column based search is not yet supported by your package by default, but I guess this could be implemented if necessary. Currently I'm using it for a project and it was rather diffcult to hook into the reset to clear the additional settings. Anyhow, if no column filters are present, it won't hurt - if there are, people will understand my request.
Second change is an addition of button icons for the `copyHtml5` and `colvis` buttons. The `copyHtml5` button will be displayed if the `copy` button is asked for in the datatables config. I added this addition in a way so that it does not change the actual implementation given by datatables.net as this would be rather inconvenient due to the size of some …

Add reset to column search and icons to copy and colvis buttons

---

src/Services/DataTable.php

I'm adding `hasScopes` method to check if the current DataTable class has the given scopes.
In my case, I have to determine the columns based on scopes. For example, it the DataTable class has a scope then I need to display A, B and C, otherwise display only A and B.
```php
/**
* Get columns.
*
* @return array
*/
protected function getColumns(): array
{
$columns = [
'A',
'B',
];
if ($this->hasScopes([MyScope::class])) {
$columns = array_merge(
$columns,
[
'C'
]
);
}
return $columns;
}
```
I'm also adding a second parameter to the `hasScopes` method, it's a boolean flag (`false` by default) to set whether to check all the values for true, or to return true if at least one class is matched.
```php
$this->hasScopes([FirstScope::class, SecondScope::class], true)
```
If we pas the second …

[4.0] Added hasScopes method.

---

src/Services/DataTable.php

This PR will allow export and print columns customised header if manually set but retains backward compatibility.
```php
protected $exportColumns = [
'email',
];
protected $printColumns = [
'email',
];
```
```php
protected $exportColumns = [
['data' => 'email', 'title' => 'Registered Email],
];
protected $printColumns = [
['data' => 'email', 'title' => 'Registered Email'],
];
````

[4.0] Allow customization of export and print columns.

---

composer.json

As Laravel Excel has changed pretty significantly, would it be possible to allow Laravel 5.7 and up to install the 3.x branch?
https://laravel-excel.maatwebsite.nl/3.1/getting-started/upgrade.html#upgrading-to-3-from-2-1
> Version 3.* is not backwards compatible with 2.*. It's not possible to provide a step-by-step migration guide as it's a complete paradigm shift.
Currently we encounter upgrade blocks mostly because of the Excel update, while there shouldn't be any major changes since 5.5. This allows to ease the upgrade process more gently :)

[3.x] Allow Laravel 5.4 and up

---

src/ButtonsServiceProvider.php
src/Contracts/DataTableHtmlBuilder.php
src/Generators/DataTablesHtmlCommand.php
src/Generators/DataTablesMakeCommand.php
src/Generators/stubs/builder.stub
src/Generators/stubs/datatables.stub
src/Generators/stubs/html.stub
src/Html/DataTableHtml.php
src/Services/DataTable.php
src/config/config.php

This PR aims to extract the `html()` method of DataTable service to its own class with the following changes:
1. Add `htmlBuider()` method that will return a `Builder` class.
2. Add generator command `datatables:html` to generate the Html Builder class.
3. Replace `html()` with `htmlBuilder()` when using the generator `datatables:make --builder` command.
4. `datatables:make --builder` command will now generate 2 files. One for the service class and one for html builder class.
5. This will also address issue for multiple dataTables rending as discussed on https://github.com/yajra/laravel-datatables/pull/995.
6. Stubs were updated to promote the fluent api and `Column` and `Button` class.
The command below will generate `UsersDataTableHtml` class with some options as needed.
```sh
> php …
```

[4.0] Extract html builder to own class.

---

src/Services/DataTable.php

Starting in Laravel 7.7.0, a BindingResolutionException is thrown when a required parameter is not found. When implementing laravel-datatables as a service, the query parameter is used in the extended classes. 
However, in the DataTable service, the parameter is called "source". This throws an exception as the required variable "query" is missing. I have changed the variable name to "query" to fix this.
Let me know, if you have any questions.
Fixes https://github.com/yajra/laravel-datatables/issues/2375
Thanks!

Fix BindingResolutionException when using Laravel 7.7.0 or greater

---

src/resources/views/print.blade.php

I had a table where the first 3 rows were identical.
Because of the `reset` call I had the header displayed three times.
Using Blade's `first` helper solves it and is working from Laravel 5.3.
https://laravel.com/docs/5.3/blade#the-loop-variable

Use Blade's helper to check for the first row

---

src/Generators/DataTablesMakeCommand.php

added support for Laravel 8.x if Models directory exists then use Models directory in namespace for model
PR for the issue [Pointing to wrong model path when generating DataTable - Laravel 8](https://github.com/yajra/laravel-datatables/issues/2468)

Added support for Laravel 8.x if Models directory exists.

---

src/Services/DataTable.php

If we don't set the start to 0, if we're press the export button from page > 1, and we're displaying row index, the row index will completely wrong.

Set the start to 0 on export

---

src/Services/DataTable.php

Improve how to determine if the current request probably expects a JSON response.
That following test can be simplified be adapting [`$request->expectsJson()`](https://github.com/laravel/framework/blob/master/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php#L24)
```diff
public function test_a_user_can_view_any_users()
{
$user = User::factory()->create();
-    $jsonResponse = $this->actingAs($user)
-        ->withHeaders([
-            'Accept' => 'application/json',
-            'X-Requested-With' => 'XMLHttpRequest',
-        ])
-        ->get(route('users.index'));
+    $jsonResponse = $this->actingAs($user)->json('GET', route('users.index'));
$jsonResponse->assertSuccessful();
$this->assertArrayNotHasKey('error', $jsonResponse->getData(true));
}
```

Request expects JSON

---

src/Exports/DataTablesCollectionExport
src/Services/DataTable.php
src/Services/DataTablesExportHandler.php

This PR will improve support for the `laravel-excel` package export class.
1. All rows will now be included instead of the filtered values displayed in the table. (Potential breaking change)
2. Add `DataTablesCollectionExport` abstract class.
1. Create an export class `php artisan make:export UsersExport`
2. Update the generated export class and extend `DataTablesCollectionExport`
```php
namespace App\Exports;
use Yajra\DataTables\Exports\DataTablesCollectionExport;
class UsersExport extends DataTablesCollectionExport
{
}
```
3. Update your `UsersDataTable` class and set `protected $exportClass = UsersExport::class`
```php
class UsersDataTable extends DataTable
{
protected $exportClass = UsersExport::class;
```
4. Update your export class as needed. See official package docs: …

[4.x] Improve support for custom laravel-excel export class using collection.

---

composer.json
src/Exports/DataTablesCollectionExport.php
src/Services/DataTable.php

Add fast export function support for https://github.com/rap2hpoutre/fast-excel package.

[4.x] Add support for fast-excel when exporting to excel and csv.

---

src/Services/DataTable.php

This PR makes sure that if you're using a custom export handler which extends the default DataTablesExportHandler, it receives the same data that the default export handler would receive.
This fixes a BC introduced on commit 45c7faf957e10cbfdfa0424d2f0b0765fbb1fd5a (see issue #126)

Use same export data if export handler extends DataTablesExportHandler

---

src/Html/DataTableHtml.php

This PR will allow `make` factory helper to accept constructor arguments like how Laravel's `Event::dispatch()` works.
```php
class ProjectMembersDataTableHtml extends DataTableHtml
{
public $project;
public function __construct(Project $project)
{
$this->project = $project;
}
...
```
Before PR:
```php
$members = (new ProjectMembersDataTableHtml($project))->handle();
```
After PR:
```php
$members = ProjectMembersDataTableHtml::make($project);
```

[4.x] Allow passing of constructor arguments on make method helper.

---

src/Services/DataTable.php

Hi! 
I'm trying to use the `addScopes` in a base class, but sounds like it's creating a array of array of scopes and not a list of scopes like in multiple calls of `addScope`.
BTW thanks for the package. I love it.

[4x.] Fix addScopes method pushing the array of scopes.

---

src/Services/DataTable.php

FastExcel Integration: Use data as source since integration relies on SQL field name / alias.

FastExcel Integration: Use data as source.

---

composer.json
src/ButtonsServiceProvider.php
src/Services/DataTable.php

Hi,
When you want to use the `fast-excel` package (or another Excel-package) instead of `maatwebsite/excel`, this package will be still installed due it's being installed in the root-required selection.
It's better to move `maatwebsite/excel` to the suggest selection, so we can pick-up one of the suggestions instead. 
Technically this /is/ a breaking change, but I don't know which branch you are using for v5, since master is little bit behind already.

Package `maatwebsite/excel` still being installed when you want to use `fast-excel` (or another Excel-package)

---

src/Contracts/DataTableScope.php
src/Services/DataTable.php

I have upgraded from v4 and the following instruction throws the exception "TypeError" because the input parameter of the applyScopes() function can be of type Relation and the returned value can also be of type Relation.
`$returnHTML = $dataTable->with(["model" => $model])->render('backend.media.get_media_datatables', $data);
`
```
exception: "TypeError"
file: "/var/app/current/vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php"
line: 719
message: "Yajra\\DataTables\\Services\\DataTable::applyScopes(): Argument #1 ($query) must be of type Illuminate\\Database\\Eloquent\\Builder|Illuminate\\Database\\Query\\Builder, Illuminate\\Database\\Eloquent\\Relations\\MorphMany given, called in /var/app/current/vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php on …
```

[10.x] Fix scopes for Eloquent Relation - Exception: "TypeError"

---

src/Generators/DataTablesHtmlCommand.php
src/Generators/DataTablesMakeCommand.php

This pull request fixes plethora of issues for the `datatables:make` command -
1. Fixes `datatables:make` command fail to generate error free classes for the following scenarios where it can't identify the model name and namespace correctly -
- `php artisan datatables:make Api/DriverDataTable`
- `php artisan datatables:make Api/Driverdatatable`
- `php artisan datatables:make Api/Driver`
- `php artisan datatables:make Api/DriverDataTable --model=Driver`
- `php artisan datatables:make Api/DriverDataTable --model=Driver --model-namespace=App\\Custom`
- `php artisan datatables:make Api/DriverDataTable --builder`
2. Fixes appending `DataTable` with mix-case or lowercase generating different class name.
4. In `datatables:make` command, the `getModel()` method was too confusing. Tried to …

Fixes some issues and confusion of datatable generator command

---

src/Contracts/DataTableScope.php
src/Services/DataTable.php

This pull request fix the issue that when we create a DataTable service from php artisan datatables:make command, the service cannot support CollectionDatatable because applyScopes method in Yajra\DataTables\Services\DataTable class only support EloquentBuilder|QueryBuilder|EloquentRelation.

fix: applyScopes method to support Collection

---

src/Services/DataTable.php

Currently, when using `FastExcel` exports within Laravel Octane, a fatal error is produced on consecutive export requests:
> PHP Fatal error:  Cannot redeclare Yajra\DataTables\Services\queryGenerator() (previously declared in /var/www/vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php:803) in /var/www/vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php on line 803
I think it should be completely safe and backwards compatible to use a variable for this scoped function instead of a named function.

fix: prevent redeclaring export query generator function (Laravel Octane)

---

src/Transformers/DataArrayTransformer.php

this commit is paired with another commit d48dc1bbe8bc860070240d6f1444e7a861c53789 which should be pushed together to make final result:
this commit is about development not bug fix:
i realize a need to render column data for export, i found it by adding Export Class to set how to render export
but i couldn't find any thing for render print
and i need a centralized render for print & export (for simplicity & integrity)
so i added exportRender method to be used for pass a callback function to determine how targeted column data should be rendered for print & export, sample code is shown below:
Column::make('used')->title('Use Status')->exportRender(function($row,$data){return $data == 1 ? 'Yes' : 'Not Yet'});
but in this commit we write just use of callback function for rendering column to …

fix: use callback function if exportRender method is set

---

phpstan.neon.dist

Ignore `Command "datatables:html" does not have option*` error

fix: static analysis

---

composer.json
phpstan.neon.dist

Starting with Larastan 2.7.0, the Larastan repository will now be managed under the Larastan organization. To ensure we receive the most recent updates, I've made the necessary updates to both the `composer.json` and `phpstan.neon.dist` files.

fix: Update composer.json to use Larastan org

---

src/Services/DataTable.php

Since fast-excel [v5.5.0](https://github.com/rap2hpoutre/fast-excel/releases/tag/v5.5.0), per cell styling is now supported.
This PR aims to support export format styling:
In your DataTable class, enable `fastExcel` then define the export format in your column definition.
```php
protected bool $fastExcel = true;
public function getColumns(): array
{
return [
\Yajra\DataTables\Html\Column::make('created_at')->exportFormat('mm/dd/yyyy'),
];
}
```

feat: fast-excel export cell styling via exportFormat

---

src/Services/DataTable.php

Since this [pull request](https://github.com/yajra/laravel-datatables-buttons/pull/186), per cell styling is supported via exportFormat() of Column class.
This pull request takes it further by supporting the exportRender() of Column when using fast excel to provide another way to modify cell data.
```php
class YourDataTable extends DataTable
{
protected bool $fastExcel = true;
public function html()
{
return $this->builder()
->columns([
\Yajra\DataTables\Html\Column::make('created_at')->exportRender(function ($row, $data) {
return \Carbon\Carbon::parse($data)->format('m/d/Y h:i a');
})
]);
}
}
```

feat: fast excel export via Column's exportRender()

---

src/Services/DataTable.php

- Fixes a redundancy in the `csv()` method where `buildExcelFile()` was called twice.
- Calling `buildExcelFile()` multiple times introduces unnecessary processing, especially for large datasets.
Fixes #192

Fix: Avoid redundant call to buildExcelFile in csv method

---

src/Services/DataTable.php
tests/DataTableServiceTest.php

This PR aims to give Yajra\DataTables\Services\DataTable base class more flexibility by adding the Illuminate\Support\Traits\Macroable trait which allows us to register custom methods.
```php
class AppServiceProvider extends ServiceProvider
{
public function boot(): void
{
Yajra\DataTables\Services\DataTable::macro('foo', fn (): string => 'bar');
}
}
$dataTable = new class extends Yajra\DataTables\Services\DataTable {}
$dataTable->foo(); // returns 'bar'
```

feat: Macroable DataTable Base Class

---

src/Services/DataTable.php
tests/DataTableServiceTest.php
tests/DataTables/UsersDataTable.php
tests/views/users.blade.php

This PR allows DataTables extending Yajra\DataTables\Services\DataTable to be passed as route action when defining routes:
```php
// web.php
Route::get('/roles', RolesDataTable::class);
// RolesDataTable
class RolesDataTable extends Yajra\DataTables\Services\DataTable
{
protected ?string $view = 'roles.index';
public function dataTable(...) {...}
public function query(...) {...}
#[\Override]
protected function viewData(): array
{
return [
'title' => 'Manage Roles',
'breadcrumbs' => [
'Administration',
'ACL',
'Roles',
],
'widgets' => view('roles.widgets'),
'rolesCount' => $this->query()->count(),
];
}
}
// roles/index.blade.php
<x-layouts.admin>
<x-slot:title>{{ $title }}</x-slot>
<x-breadcrumbs>
@foreach($breadcrumbs as $breadcrumb)
<x-breadcrumbs.item>{{ $breadcrumb …
```

feat: DataTable as route action
