yajra/laravel-datatables-buttons

src/Contracts/DataTableContract.php
src/Generators/stubs/datatables.stub
src/Services/DataTable.php

Enhance DataTable for reusability.

---

src/resources/assets/buttons.server-side.js

Fix https://github.com/yajra/laravel-datatables/issues/1049

Fix url params.

---

composer.json
src/Generators/stubs/datatables.stub

Fix random issues occurring due to long URL.
Fix/Lessen IE compatibility issue due to long URL limitation.

Use minifiedAjax by default.

---

src/Services/DataTable.php

Hello,
i'm adding addScopes function, to push multiples scopes to the query scope array in one go.
i think it's useful to avoid multiple addScope chaining.
thanks.

Adding addScopes function to Services/DataTables

---

src/Generators/stubs/datatables.stub

`DataTables::make()` can handle configured engine.

[3.0] Use datatables() helper to create dataTable instance.

---

src/Generators/stubs/datatables.stub
src/config/config.php

[3.0] Use default builder parameters from config.

---

src/Generators/DataTablesScopeCommand.php

[3.0] Handle scopes stub folder config.

---

src/ButtonsServiceProvider.php

ref https://github.com/yajra/laravel-datatables/pull/1444 , https://github.com/yajra/laravel-datatables/pull/1445

[3.0] Fix ButtonsServiceProvider

---

README.md

Add patreon link.

---

src/Generators/stubs/datatables.stub

Related issues:
- https://github.com/yajra/laravel-datatables/issues/1519
- #19

Specify selected columns to avoid issues like #19.

---

composer.json

Added Laravel 5.6 Support

---

src/Transformers/DataArrayTransformer.php

[3.0] Keep original type in exportable array.

---

composer.json

[4.0] Set minimum version to Laravel 5.5+

---

composer.json

https://github.com/yajra/laravel-datatables/pull/2002

Add support for dataTables v9.0.

---

composer.json
src/Generators/DataTablesMakeCommand.php
src/Transformers/DataArrayTransformer.php

[4.0] Add support Laravel 6.0 & remove deprecated functions.

---

composer.json

Remove constraint on console, Laravel version will depend on core package.

Add support for Laravel 8.

---

README.md

Add Laravel DataTables 9.x on requirements.

---

src/Services/DataTable.php

Reverts yajra/laravel-datatables-buttons#120 as it breaks several installations.

Revert "Request expects JSON"

---

src/Services/DataTable.php

Fix checking of custom export handler.

---

src/Transformers/DataArrayTransformer.php

Fix export with array values.

---

composer.json

Update the package "maatwebsite/excel" to 3.1 ,

Update the maatwebsite/excel

---

CONTRIBUTING.md

Add conributing.md

---

src/Services/DataTable.php

Correcting with parameter typehints

---

composer.json

Related: https://github.com/nunomaduro/larastan/issues/1355

fix(phpstan) Downgrade to 2.1.12

---

src/Services/DataTable.php

When I click the print button, the print view was not called because 'printPreview' is not in the $this->actions.

fix: Change for correct $action and $actionMethod

---

src/Contracts/DataTableScope.php
src/Services/DataTable.php

Related PR
- https://github.com/yajra/laravel-datatables/pull/2944
- https://github.com/yajra/laravel-datatables-buttons/pull/168

fix: scopes when using api resource

---

src/Generators/stubs/builder.stub
src/Generators/stubs/datatables.stub
src/Generators/stubs/html.stub
src/config/config.php

fix: stubs - remove redundant docs

---

src/Services/DataTable.php

Add a dev-friendly error message when using export.
**Integrated packages:**
- FastExcel
- LaravelExcel
- LaravelSnappy

fix: export package integration error message

---

src/Services/DataTable.php

Fix error when exporting with eager loaded models

fix: exporting of related models

---

src/Services/DataTable.php

Hello,
I created a custom ajax action, but it unfortunately does not work because the default ajax action takes the priority on custom actions.
This PR fixes that issue.

fix: custom ajax action
